// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjsnIvYHVCZlo0WvxOrLXoVlGXn3BDZNs',
    appId: '1:522359238633:web:65d0bf34b2aa59905f2578',
    messagingSenderId: '522359238633',
    projectId: 'boooka-eff8e',
    authDomain: 'boooka-eff8e.firebaseapp.com',
    storageBucket: 'boooka-eff8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7dRmYf6c9pS1N7eVDi6NWAZtik99h9o',
    appId: '1:522359238633:android:7124d1e2970819cb5f2578',
    messagingSenderId: '522359238633',
    projectId: 'boooka-eff8e',
    storageBucket: 'boooka-eff8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP40xfXWD8IUEj1o6xoKtYUJOf-EOuPv8',
    appId: '1:522359238633:ios:73cef07656d2f63a5f2578',
    messagingSenderId: '522359238633',
    projectId: 'boooka-eff8e',
    storageBucket: 'boooka-eff8e.appspot.com',
    iosClientId: '522359238633-10k2g1p2k17hb91knm3j7lhkvnqvenrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.boookaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP40xfXWD8IUEj1o6xoKtYUJOf-EOuPv8',
    appId: '1:522359238633:ios:73cef07656d2f63a5f2578',
    messagingSenderId: '522359238633',
    projectId: 'boooka-eff8e',
    storageBucket: 'boooka-eff8e.appspot.com',
    iosClientId: '522359238633-10k2g1p2k17hb91knm3j7lhkvnqvenrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.boookaa',
  );
}
